# Generated by Django 4.2.7 on 2023-11-13 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ppl",
            fields=[
                (
                    "nu",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("apellidos_nombres", models.CharField(max_length=100)),
                (
                    "patio",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
    ]
